.image:
    image: 
        name: $IMAGE
        entrypoint: ["start.sh"]

    before_script:
    - conda env update -n base -f ./binder/environment.yml
    
    tags: [data, docker]

stages:
- ingest

fullscan:
    extends: .image
    stage: ingest
    script: 
    - datalabframework run --timeout=-1 --profile=prod src/fullscan.ipynb 
    when: manual
  
daily:
    extends: .image
    stage: ingest
    script: 
    - datalabframework run --timeout=-1 --profile=prod src/daily.ipynb 
    only:
    - schedules
    - web
